import { RecipeModel } from './models';
export const MOCK_RECIPES: RecipeModel[] = [
    {
        id: 1,
        name: 'Spaghetti Carbonara',
        description: 'A classic Italian pasta dish.',
        imgUrl: 'https://placehold.co/600x400/E8117F/white?text=Spaghetti+Carbonara',
        authorEmail: 'mario@italy.com',
        isFavorite: true, 
        ingredients: [
            { name: 'Spaghetti', quantity: 200, unit: 'g' },
            { name: 'Guanciale', quantity: 100, unit: 'g' },
            { name: 'Egg Yolks', quantity: 4, unit: 'each' },
            { name: 'Pecorino Romano Cheese', quantity: 50, unit: 'g' },
            { name: 'Black Pepper', quantity: 1, unit: 'tsp' },
        ],
    },
    {
        id: 2,
        name: 'Caprese Salad',
        description: 'A simple and refreshing Italian salad.',
        imgUrl: 'https://placehold.co/600x400/40C463/white?text=Caprese+Salad',
        authorEmail: 'luigi@italy.com', 
        isFavorite: false, 
        ingredients: [
            { name: 'Tomatoes', quantity: 4, unit: 'each' },
            { name: 'Fresh Mozzarella', quantity: 200, unit: 'g' },
            { name: 'Fresh Basil', quantity: 1, unit: 'bunch' },
            { name: 'Extra Virgin Olive Oil', quantity: 2, unit: 'tbsp' },
        ],
    },
    {
        id: 3,
        name: 'Chicken Tikka Masala',
        description: 'Creamy and aromatic Indian curry with tender chicken pieces.',
        imgUrl: 'https://placehold.co/600x400/FF6B35/white?text=Chicken+Tikka+Masala',
        authorEmail: 'raj@india.com',
        isFavorite: true,
        ingredients: [
            { name: 'Chicken Breast', quantity: 500, unit: 'g' },
            { name: 'Yogurt', quantity: 200, unit: 'ml' },
            { name: 'Tomato Puree', quantity: 300, unit: 'ml' },
            { name: 'Heavy Cream', quantity: 150, unit: 'ml' },
            { name: 'Garam Masala', quantity: 2, unit: 'tsp' },
            { name: 'Ginger', quantity: 2, unit: 'tbsp' },
            { name: 'Garlic', quantity: 3, unit: 'cloves' },
        ],
    },
    {
        id: 4,
        name: 'Margherita Pizza',
        description: 'Classic Italian pizza with fresh mozzarella, tomatoes, and basil.',
        imgUrl: 'https://placehold.co/600x400/00A652/white?text=Margherita+Pizza',
        authorEmail: 'giuseppe@italy.com',
        isFavorite: false,
        ingredients: [
            { name: 'Pizza Dough', quantity: 300, unit: 'g' },
            { name: 'Tomato Sauce', quantity: 150, unit: 'ml' },
            { name: 'Fresh Mozzarella', quantity: 200, unit: 'g' },
            { name: 'Fresh Basil', quantity: 10, unit: 'leaves' },
            { name: 'Extra Virgin Olive Oil', quantity: 2, unit: 'tbsp' },
            { name: 'Salt', quantity: 1, unit: 'tsp' },
        ],
    },
    {
        id: 5,
        name: 'Beef Tacos',
        description: 'Mexican-style tacos with seasoned ground beef and fresh toppings.',
        imgUrl: 'https://placehold.co/600x400/8B4513/white?text=Beef+Tacos',
        authorEmail: 'carlos@mexico.com',
        isFavorite: true,
        ingredients: [
            { name: 'Ground Beef', quantity: 400, unit: 'g' },
            { name: 'Taco Shells', quantity: 8, unit: 'each' },
            { name: 'Lettuce', quantity: 1, unit: 'head' },
            { name: 'Tomatoes', quantity: 2, unit: 'each' },
            { name: 'Cheddar Cheese', quantity: 150, unit: 'g' },
            { name: 'Sour Cream', quantity: 200, unit: 'ml' },
            { name: 'Taco Seasoning', quantity: 2, unit: 'tbsp' },
        ],
    },
    {
        id: 6,
        name: 'Thai Green Curry',
        description: 'Aromatic and spicy Thai curry with vegetables and coconut milk.',
        imgUrl: 'https://placehold.co/600x400/228B22/white?text=Thai+Green+Curry',
        authorEmail: 'somchai@thailand.com',
        isFavorite: false,
        ingredients: [
            { name: 'Green Curry Paste', quantity: 3, unit: 'tbsp' },
            { name: 'Coconut Milk', quantity: 400, unit: 'ml' },
            { name: 'Chicken Thighs', quantity: 300, unit: 'g' },
            { name: 'Thai Basil', quantity: 1, unit: 'cup' },
            { name: 'Fish Sauce', quantity: 2, unit: 'tbsp' },
            { name: 'Palm Sugar', quantity: 1, unit: 'tbsp' },
            { name: 'Eggplant', quantity: 1, unit: 'each' },
        ],
    },
    {
        id: 7,
        name: 'French Onion Soup',
        description: 'Classic French soup with caramelized onions and melted cheese.',
        imgUrl: 'https://placehold.co/600x400/8B4513/white?text=French+Onion+Soup',
        authorEmail: 'pierre@france.com',
        isFavorite: true,
        ingredients: [
            { name: 'Yellow Onions', quantity: 6, unit: 'each' },
            { name: 'Beef Broth', quantity: 1, unit: 'liter' },
            { name: 'Gruyere Cheese', quantity: 200, unit: 'g' },
            { name: 'French Bread', quantity: 1, unit: 'baguette' },
            { name: 'Butter', quantity: 4, unit: 'tbsp' },
            { name: 'Dry White Wine', quantity: 100, unit: 'ml' },
            { name: 'Thyme', quantity: 2, unit: 'sprigs' },
        ],
    },
    {
        id: 8,
        name: 'Sushi Rolls',
        description: 'Fresh Japanese sushi rolls with salmon and avocado.',
        imgUrl: 'https://placehold.co/600x400/FF69B4/white?text=Sushi+Rolls',
        authorEmail: 'yuki@japan.com',
        isFavorite: false,
        ingredients: [
            { name: 'Sushi Rice', quantity: 300, unit: 'g' },
            { name: 'Nori Sheets', quantity: 4, unit: 'sheets' },
            { name: 'Fresh Salmon', quantity: 200, unit: 'g' },
            { name: 'Avocado', quantity: 1, unit: 'each' },
            { name: 'Cucumber', quantity: 1, unit: 'each' },
            { name: 'Rice Vinegar', quantity: 3, unit: 'tbsp' },
            { name: 'Wasabi', quantity: 1, unit: 'tsp' },
            { name: 'Soy Sauce', quantity: 2, unit: 'tbsp' },
        ],
    },
];
